
import Navbar from "@/Navbar";
import "./globals.css";
import Footer from "@/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="w-full overflow-x-hidden relative"
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
